#define BRIG_PHYSICIAN		(1<<14)
#define PRISONER		(1<<15)
#define DRIFTER	 	(1<<16)

#define JOB_DISPLAY_ORDER_BRIG_PHYSICIAN 33
#define JOB_DISPLAY_ORDER_PRISONER 34
#define JOB_DISPLAY_ORDER_DRIFTER 35
#define BLUESHIELD		(1<<15)
#define PRISONER		(1<<16)

#define JOB_DISPLAY_ORDER_BRIG_PHYSICIAN 33
#define JOB_DISPLAY_ORDER_BLUESHIELD 34
#define JOB_DISPLAY_ORDER_PRISONER 35
