#define BRIG_PHYSICIAN		(1<<14)
#define PRISONER		(1<<15)
#define BLUESHIELD		(1<<16)


#define JOB_DISPLAY_ORDER_BRIG_PHYSICIAN 34
#define JOB_DISPLAY_ORDER_PRISONER 36
#define JOB_DISPLAY_ORDER_BLUESHIELD 34