/obj/item/organ/regenerative_core/afterattack(atom/target, mob/user, proximity_flag)
	if(proximity_flag)
		if(istype(target, /mob/living/simple_animal/hostile/megafauna/bubblegum))
			new /mob/living/simple_animal/hostile/megafauna/bubblegum/hard(target.loc)
			visible_message("[user] turned [target] into an enraged [target]!")
			qdel(target)
			qdel(src)
		else if(istype(target, /mob/living/simple_animal/hostile/megafauna/dragon))
			new /mob/living/simple_animal/hostile/megafauna/dragon/hard(target.loc)
			visible_message("[user] turned [target] into an enraged [target]!")
			qdel(target)
			qdel(src)
		else if(istype(target, /mob/living/simple_animal/hostile/megafauna/legion))
			new /mob/living/simple_animal/hostile/megafauna/legion/hard(target.loc)
			visible_message("[user] turned [target] into an enraged [target]!")
			qdel(target)
			qdel(src)
		else
			apply_healing_core(target, user)
