#define COMSIG_ITEM_ITEMINFO "iteminfo"
#define COMSIG_LIVING_STOP_PULLING "stop_pulling"
#define COMSIG_LIVING_STOP_GRABBING "stop_grabbing"
#define COMSIG_LIVING_GAIN_UNCONSCIOUS "gain_unconscious"
#define COMSIG_LIVING_STOP_UNCONSCIOUS "stop_unconscious"
